import Button from '../components/Button'
import HStack from '../components/HStack'
import Image from '../components/Image'
import Text from '../components/Text'
import TextField from '../components/TextField'
import VStack from '../components/VStack'
import { type ComponentDefinition, ComponentType } from './common'

const componentRegistry: Record<ComponentType, ComponentDefinition> = {
  [ComponentType.Button]: Button,
  [ComponentType.Text]: Text,
  [ComponentType.VStack]: VStack,
  [ComponentType.HStack]: HStack,
  [ComponentType.TextField]: TextField,
  [ComponentType.Image]: Image,
  // [ComponentType.Slider]: Slider,
  // [ComponentType.Toggle]: Toggle,
  // [ComponentType.ProgressBar]: ProgressBar,
  // [ComponentType.ZStack]: ZStack,
  // [ComponentType.LazyVGrid]: LazyVGrid,
  // [ComponentType.LazyHGrid]: LazyHGrid,
  // [ComponentType.ScrollView]: ScrollView,
  // [ComponentType.List]: List,
  // [ComponentType.NavigationView]: NavigationView,
  // [ComponentType.TabView]: TabView,
  // [ComponentType.Sheet]: Sheet,
  // [ComponentType.Alert]: Alert,
  // [ComponentType.ActionSheet]: ActionSheet,
  // [ComponentType.Rectangle]: Rectangle,
  // [ComponentType.Circle]: Circle,
  // [ComponentType.RoundedRectangle]: RoundedRectangle,
  // [ComponentType.Capsule]: Capsule,
  // [ComponentType.Ellipse]: Ellipse,
  // [ComponentType.Form]: Form,
  // [ComponentType.Section]: Section,
  // [ComponentType.Picker]: Picker,
  // [ComponentType.Stepper]: Stepper,
  // [ComponentType.DatePicker]: DatePicker,
  // [ComponentType.ColorPicker]: ColorPicker,
  // [ComponentType.LazyColumn]: LazyColumn,
  // [ComponentType.LazyRow]: LazyRow,
  // [ComponentType.Box]: Box,
  // [ComponentType.Card]: Card,
  // [ComponentType.Scaffold]: Scaffold,
  // [ComponentType.TopAppBar]: TopAppBar,
  // [ComponentType.BottomNavigation]: BottomNavigation,
  // [ComponentType.FloatingActionButton]: FloatingActionButton,
  // [ComponentType.Container]: Container,
  // [ComponentType.Padding]: Padding,
  // [ComponentType.Center]: Center,
  // [ComponentType.Align]: Align,
  // [ComponentType.Expanded]: Expanded,
  // [ComponentType.Flexible]: Flexible,
  // [ComponentType.Wrap]: Wrap,
  // [ComponentType.ListView]: ListView,
  // [ComponentType.GridView]: GridView,
  // [ComponentType.AppBar]: AppBar,
  // [ComponentType.Drawer]: Drawer,
  // [ComponentType.BottomNavigationBar]: BottomNavigationBar,
  // [ComponentType.FloatingActionButton_Flutter]: FloatingActionButton_Flutter,
  // [ComponentType.View]: View,
  // [ComponentType.SafeAreaView]: SafeAreaView,
  // [ComponentType.FlatList]: FlatList,
  // [ComponentType.SectionList]: SectionList,
  // [ComponentType.Modal]: Modal,
  // [ComponentType.StatusBar]: StatusBar,
}

export default componentRegistry